name: gan-efficient-breast-cancer-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - scikit-learn>=0.24.0
  - numpy>=1.19.0,<1.22
  - matplotlib>=3.4.0
  - seaborn>=0.11.0
  - pip
  - pip:
      - opencv-python
      - python-dotenv
      - imgaug==0.4.0
      - tensorflow-macos==2.15.0
      - tensorflow-metal==1.1.0
